# Generated by Django 3.2.15 on 2022-10-08 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_borrow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='product',
            new_name='book',
        ),
    ]
