# Generated by Django 3.2.15 on 2022-10-27 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20221027_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='due_back',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='status',
        ),
    ]
